// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwojeuoogughdiehsrei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3b2pldW9vZ3VnaGRpZWhzcmVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MjkwNjEsImV4cCI6MjA1NjMwNTA2MX0.ok7b8Kbu1Z-FIZAC_eL1yfNRw6J-dgEsufYlWd7S31U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);